#!/bin/bash

set -e

# Other dpkg diversions
function do_diversion {
    # gmusicbrowser layout
    dpkg-divert --package netrunner-settings-applications --add --rename --divert /usr/share/gmusicbrowser/layouts/main.layout.orig /usr/share/gmusicbrowser/layouts/main.layout
    dpkg-divert --package netrunner-settings-applications --add --rename --divert /usr/share/gmusicbrowser/layouts/filterfun.layout.orig /usr/share/gmusicbrowser/layouts/filterfun.layout
    dpkg-divert --package netrunner-settings-applications --add --rename --divert /usr/share/gmusicbrowser/layouts/contrib.layout.orig /usr/share/gmusicbrowser/layouts/contrib.layout
    dpkg-divert --package netrunner-settings-applications --add --rename --divert /usr/share/gmusicbrowser/layouts/makeitlooklike.layout.orig /usr/share/gmusicbrowser/layouts/makeitlooklike.layout
    dpkg-divert --package netrunner-settings-applications --add --rename --divert /usr/share/gmusicbrowser/layouts/shimmer.layout.orig /usr/share/gmusicbrowser/layouts/shimmer.layout
    # gmusicbrowser main config file
    dpkg-divert --package netrunner-settings-applications --add --rename --divert /usr/share/gmusicbrowser/gmbrc.default.orig /usr/share/gmusicbrowser/gmbrc.default
}

if [ install = "$1" -o upgrade = "$1" ]; then
   do_diversion
fi
